-- This config file was made by editing the standard autogenerated one
-- You can split this configuration into multiple files
-- Create your files separately and then link them to this file like this:
-- source = ~/.config/hypr/myColors.conf

--###############
--## MONITORS ###
--###############
-- See https://wiki.hyprland.org/Configuring/Monitors/

hl.monitor({
	output = "",
	mode = "highrr",
	position = "auto",
	scale = "auto",
})

-- monitor= desc:Huawei Technologies Co. Inc. ZQE-CAA 0xC080F622, highrr, auto, 1.6

-- # # trigger when the switch is turning off
-- bindl = , switch:off:Lid Switch,exec,hyprctl keyword monitor "eDP-1,highrr,auto,auto,bitdepth,10"
-- # trigger when the switch is turning on
-- bindl = , switch:on:Lid Switch,exec,hyprctl keyword monitor "eDP-1, disable"

--##################
--## MY PROGRAMS ###
--##################

local terminal = "ghostty"
local fileManager = "dolphin"
local menu = "rofi -show drun"
local browser = "firefox"

--############################
--## ENVIRONMENT VARIABLES ###
--############################

-- See https://wiki.hyprland.org/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", 24)
hl.env("HYPRCURSOR_SIZE", 24)
hl.env("GDK_SCALE", 2)
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("XDG_MENU_PREFIX", "arch-")
hl.env("QT_QPA_PLATFORM", "wayland")
hl.env("SDL_VIDEODRIVER", "wayland")
hl.env("MOZ_ENABLE_WAYLAND", 1)

--##################
--## PERMISSIONS ###
--##################

-- See https://wiki.hyprland.org/Configuring/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly

-- for security reasons
-- ecosystem {
--   enforce_permissions = 1
-- }

-- permission = /usr/(bin|local/bin)/grim, screencopy, allow
-- permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
-- permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

-- Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- workspace = w[tv1], gapsout:0, gapsin:0
-- workspace = f[1], gapsout:0, gapsin:0
-- windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
-- windowrule = rounding 0, floating:0, onworkspace:w[tv1]
-- windowrule = bordersize 0, floating:0, onworkspace:f[1]
-- windowrule = rounding 0, floating:0, onworkspace:f[1]

--############
--## INPUT ###
--############

-- https://wiki.hyprland.org/Configuring/Variables/#input

hl.config({
	xwayland = {
		force_zero_scaling = true,
	},
	general = {
		gaps_in = 2,
		gaps_out = 5,
		border_size = 2,
		col = {
			active_border = { colors = { "rgba(33aaffee)", "rgba(aa0099ee)" }, angle = 90 },
			inactive_border = "rgba(595959aa)",
		},

		layout = "dwindle",
	},
	animations = { enabled = true },
	decoration = {
		rounding = 6,
		rounding_power = 2,
		-- Change transparency of focused and unfocused windows
		active_opacity = 1.0,
		inactive_opacity = 0.9,
		shadow = {
			enabled = false,
			range = 4,
			render_power = 3,
			color = "rgba(1a1a1aee)",
		},
		-- https://wiki.hyprland.org/Configuring/Variables/#blur
		blur = {
			enabled = false, -- Improving battery life
			size = 5,
			passes = 1,
			vibrancy = 0.1696,
		},
	},
	dwindle = {
		preserve_split = true, -- You probably want this
	},
	misc = {
		force_default_wallpaper = 0, -- Set to 0 or 1 to disable the anime mascot wallpapers
		disable_hyprland_logo = true, -- If true disables the random hyprland logo / anime girl background. :(
		animate_manual_resizes = true,
	},
	master = {
		new_status = "master",
	},
	input = {
		kb_layout = "us,it,ru",
		kb_variant = "",
		kb_model = "",
		kb_options = "caps:escape_shifted_capslock,grp:alt_shift_toggle",
		kb_rules = "",
		follow_mouse = 1,
		sensitivity = -0.2, -- -1.0 - 1.0, 0 means no modification.
		touchpad = {
			natural_scroll = true,
		},
		repeat_delay = 250,
		repeat_rate = 60,
	},
})

-- https://wiki.hyprland.org/Configuring/Variables/#gestures

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace"
})

hl.gesture({
    fingers = 3,
    direction = "up",
    action = "fullscreen"
})

-- Example per-device config
-- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more

--##################
--## KEYBINDINGS ###
--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/

local mainMod = "SUPER"

-- Sets "Windows" key as main modtrue
-- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more

hl.bind(mainMod .. " + " .. "T", hl.dsp.exec_cmd("ghostty"))
hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "M", hl.dsp.exit())
hl.bind(mainMod .. " + " .. "M", hl.dsp.exec_cmd("hyprlock"))
hl.bind(mainMod .. " + " .. "G", hl.dsp.exec_cmd("firefox"))
hl.bind(mainMod .. " + " .. "E", hl.dsp.exec_cmd("dolphin"))
hl.bind(mainMod .. " + " .. "V", hl.dsp.window.float())
hl.bind(mainMod .. " + " .. "R", hl.dsp.exec_cmd("rofi -show drun"))

-- bind = $mainMod, D, pseudo, # dwindle
hl.bind(mainMod .. " + " .. "F", hl.dsp.window.fullscreen())
hl.bind(mainMod .. " + " .. "period", hl.dsp.exec_cmd("rofi -show filebrowser"))
-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + " .. "H", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + " .. "L", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + " .. "K", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + " .. "J", hl.dsp.focus({ direction = "down" }))

-- Switch workspaces with mainMod + [0-9]
hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))

-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(mainMod .. " + " .. key,             hl.dsp.focus({ workspace = i}))
    hl.bind(mainMod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i }))
end
hl.bind(mainMod .. " + " .. "Tab", hl.dsp.focus({ workspace = "previous" }))

-- to switch between tabs in all workspaces (like gnome)

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + shift + H/L
hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "L", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + " .. "CTRL" .. " + " .. "H", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Resizing windows with vim motions

-- hl.bind("$mainMod + SHIFT + L", hl.dsp.resize("20 0"))
-- hl.bind("$mainMod + SHIFT + H", hl.dsp.resize("-20 0"))
-- hl.bind("$mainMod + SHIFT + K", hl.dsp.resize("0 -20"))
-- hl.bind("$mainMod + SHIFT + J", hl.dsp.resize("0 20"))
--
-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 3%+"), { locked = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 3%-"), { locked = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 1%+"), { locked = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 1%-"), { locked = true })

-- Requires playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

--#############################
--## WINDOWS AND WORKSPACES ###
--#############################

-- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
-- See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules
-- Example windowrule
-- windowrule = float,class:^(kitty)$,title:^(kitty)$
-- Ignore maximize requests from apps. You'll probably like this.
-- windowrule = suppressevent maximize, class:.*
-- Fix some dragging issues with XWayland
-- windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
hl.bind("CTRL" .. " + " .. "F5", hl.dsp.exec_cmd("hyprctl hyprsunset temperature 3600"), { locked = true })
hl.bind("CTRL" .. " + " .. "F6", hl.dsp.exec_cmd("hyprctl hyprsunset temperature 5000"), { locked = true })

-- Screenshot a window
hl.bind(mainMod .. " + " .. "P", hl.dsp.exec_cmd("hyprshot -m window -o ~/Photos/Screenshots/"))
-- Screenshot a monitor
hl.bind(
	mainMod .. " + " .. "CTRL + SHIFT" .. " + " .. "P",
	hl.dsp.exec_cmd("hyprshot -m output -o ~/Photos/Screenshots/")
)
-- Screenshot a region
hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "P", hl.dsp.exec_cmd("hyprshot -m region -o ~/Photos/Screenshots/"))

-- layerrule = ignorezero, $terminal
-- layerrule = ignorealpha 0.5, $terminal

-- Autostart
hl.on("hyprland.start", function()
	hl.exec_cmd("waybar & hyprsunset & ghostty & firefox & hypridle & swaync")
	hl.exec_cmd("~/.config/hypr/Scripts/wallpaper_loop.sh")
	hl.exec_cmd("~/.config/hypr/Scripts/battery_low_notification.sh")
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
end)
